### ISSUE TITLE
Add Support for RabbitMq.Client v7.x

### ISSUE THREAD

**Issue by WoozChucky** [ArieGato/serilog-sinks-rabbitmq#216]
**Is your feature request related to a problem? Please describe.**
Since I updated my project that also makes use of the RabbitMq.Client library to version 7.0, the sink no longer works and throws a MissingMethodException.

I've tried going back to version 6.8.3 or RabbitMq.Client and the issue goes away.
That's not a long term solution as we already migrated much of our codebase to 7.0 wich introduces breaking changes in the RabbitMq.Client public api.

**Describe the solution you'd like**
Updated the Sink code that makes use of the RabbitMq.Client version 7.x

**Describe alternatives you've considered**
Forked repo and working on updating myself.

**Additional context**
Code sample that throws the exception:
![image](https://github.com/user-attachments/assets/a04122e5-a48b-4dc0-a1df-33192b937600)
```csharp
System.MissingMethodException: Method not found: 'Void RabbitMQ.Client.ConnectionFactory.set_AuthMechanisms(System.Collections.Generic.IList`1<RabbitMQ.Client.IAuthMechanismFactory>)'.
   at Serilog.Sinks.RabbitMQ.RabbitMQConnectionFactory.GetConnectionFactory()
   at Serilog.Sinks.RabbitMQ.RabbitMQConnectionFactory..ctor(RabbitMQClientConfiguration rabbitMQConfiguration, CancellationTokenSource cancellationTokenSource) in /_/src/Serilog.Sinks.RabbitMQ/Sinks/RabbitMQ/RabbitMQConnectionFactory.cs:line 35
   at Serilog.Sinks.RabbitMQ.RabbitMQClient..ctor(RabbitMQClientConfiguration configuration) in /_/src/Serilog.Sinks.RabbitMQ/Sinks/RabbitMQ/RabbitMQClient.cs:line 39
   at Serilog.Sinks.RabbitMQ.RabbitMQSink..ctor(RabbitMQClientConfiguration configuration, RabbitMQSinkConfiguration rabbitMQSinkConfiguration, ILogEventSink failureSink) in /_/src/Serilog.Sinks.RabbitMQ/Sinks/RabbitMQ/RabbitMQSink.cs:line 46
   at Serilog.LoggerConfigurationRabbitMQExtensions.GetPeriodicBatchingSink(RabbitMQClientConfiguration clientConfiguration, RabbitMQSinkConfiguration sinkConfiguration, ILogEventSink failureSink) in /_/src/Serilog.Sinks.RabbitMQ/LoggerConfigurationRabbitMQExtensions.cs:line 363
   at Serilog.LoggerConfigurationRabbitMQExtensions.RegisterSink(LoggerSinkConfiguration loggerSinkConfiguration, RabbitMQClientConfiguration clientConfiguration, RabbitMQSinkConfiguration sinkConfiguration, Action`1 failureSinkConfiguration) in /_/src/Serilog.Sinks.RabbitMQ/LoggerConfigurationRabbitMQExtensions.cs:line 330
   at Serilog.LoggerConfigurationRabbitMQExtensions.RabbitMQ(LoggerSinkConfiguration loggerConfiguration, String[] hostnames, String username, String password, String exchange, String exchangeType, RabbitMQDeliveryMode deliveryMode, String routeKey, Int32 port, String vHost, String clientProvidedName, UInt16 heartbeat, Boolean sslEnabled, String sslServerName, SslProtocols sslVersion, SslPolicyErrors sslAcceptablePolicyErrors, Boolean sslCheckCertificateRevocation, Int32 batchPostingLimit, TimeSpan period, Nullable`1 queueLimit, ITextFormatter formatter, Boolean autoCreateExchange, Int32 maxChannels, LogEventLevel levelSwitch, EmitEventFailureHandling emitEventFailure, Action`1 failureSinkConfiguration) in /_/src/Serilog.Sinks.RabbitMQ/LoggerConfigurationRabbitMQExtensions.cs:line 181
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by ArieGato** [comment]
@WoozChucky thanks for report this issue. There's an issue for this already. #156

**Comment by ArieGato** [comment]
@WoozChucky New version has been released with RabbitMQ Client 7 support

**Comment by WoozChucky** [comment]
> @WoozChucky New version has been released with RabbitMQ Client 7 support

Thank you very much, will test it after Xmas and get back to you with feedback!  Happy holidays 🎄

**Comment by WoozChucky** [comment]
@ArieGato Conpletely forgot to reply back. So far it is working wonderfully , been using it for the past 2 weeks without any issues 👍
